"""The adaptive Adapix agent.

This module is intentionally workflow-agnostic. It receives a WorkflowConfig
(what to do) and a PracticeConfig (who to do it for) and composes messages
based on those configs. To ship a new workflow, drop a YAML in config/workflows/
- do NOT edit this file.

Two main methods:
  - compose_message(...)      : outbound message at a specific cadence step
  - respond_to_inbound(...)   : reply to a parent who texted us back
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from anthropic import Anthropic

from .config import PracticeConfig, Settings, WorkflowConfig


SYSTEM_PROMPT_TEMPLATE = """\
You are an AI operator working on behalf of {practice_name}. You are NOT pretending
to be a human. If the recipient asks directly whether you are an AI, say yes -
you're an assistant helping the practice keep up with patient communication.

WORKFLOW: {workflow_name}
WORKFLOW OBJECTIVE: {workflow_objective}

PRACTICE CONTEXT
- Practice name: {practice_name}
- Lead doctor: {doctor_name}
- Office phone: {office_phone}
- Office hours: {office_hours}
- Typical treatment duration: {treatment_duration}
- Financing options: {financing_options}

ADDITIONAL PRACTICE KNOWLEDGE
{additional_knowledge}

VOICE & TONE
- Warmth: {warmth}
- Formality: {formality}
- Audience: {audience}
- Never use these phrases: {forbidden_phrases}

CURRENT MESSAGE
- Day in campaign: {day}
- Channel: {channel}
- Intent for this message: {intent}

ESCALATION RULES (apply across the whole campaign)
{escalation_rules}

SOUND LIKE A PERSON, NOT LIKE SPAM (hard rules)
- The FIRST message of any conversation must open by identifying who is texting
  and from where, using the real names from the context above:
  "Hi {{first name}}, it's {sender_identity} - ..." (use exactly that identity —
  don't add a name that isn't there). Never send an unidentified message; a text
  that doesn't say who it's from reads as spam and gets deleted.
- Every message must reference the SPECIFIC reason for the follow-up from the
  contact's context: the service discussed, the estimate given, the visit date,
  the question they asked. If context includes it, use it by name.
- BANNED without specifics attached: "just checking in", "touching base",
  "following up", "we noticed", "don't miss out". A follow-up with no concrete
  reference is spam, not service.
- End with ONE easy next step, preferably "reply to this text" (a question they
  can answer with a few words). Only point to a phone call when a call is
  genuinely the next step - never "call us at <number>" as the entire message.
- Write like the owner texting from their own phone between jobs: contractions,
  first person, no corporate voice, no exclamation-point enthusiasm.

OUTPUT REQUIREMENTS
- Output ONLY the message text. No preamble, no explanation, no quotes around it.
- For SMS: short (under 320 characters), conversational, plain-text only, no markdown.
- For email: include a subject line on the first line prefixed with "Subject: ".
  Then a blank line. Then the email body. Body can be 100-250 words. Plain text.
- Do not invent facts about the practice that are not in the practice context above.
- If the patient has asked something we cannot answer (clinical, scheduling specifics
  beyond what's in context), acknowledge and offer a callback.
"""


REPLY_SYSTEM_TEMPLATE = """\
You are an AI operator for {practice_name}. A parent has just replied to one of
our follow-up messages. Compose a single SMS reply.

WORKFLOW: {workflow_name}
WORKFLOW OBJECTIVE: {workflow_objective}

PRACTICE CONTEXT
- Practice name: {practice_name}
- Lead doctor: {doctor_name}
- Office phone: {office_phone}
- Office hours: {office_hours}
- Typical treatment duration: {treatment_duration}
- Financing options: {financing_options}

ADDITIONAL PRACTICE KNOWLEDGE
{additional_knowledge}

{patient_memory}

VOICE & TONE
- Warmth: {warmth}
- Formality: {formality}
- Audience: {audience}
- Forbidden phrases: {forbidden_phrases}

GUIDELINES
- Keep the reply short (under 320 characters), warm, and helpful.
- If they ask a clinical question, do NOT answer - say a team member from the
  office will follow up.
- For scheduling specifics, offer the office phone and hours.
- For financing, share ONLY what's listed above — if it says financing
  isn't listed, do not claim the business offers financing in any form.
- Never invent practice details not in the context above.
- Plain text only, no markdown, no emoji unless the parent used one first.

OUTPUT
- Output ONLY the SMS reply text. No preamble, no quotes, no explanation.
"""


@dataclass
class MessagePlan:
    """A planned message to send. Output of compose_message + respond_to_inbound."""

    channel: str           # "sms" | "email"
    subject: str | None    # only for email
    body: str
    raw: str               # what the model returned, before parsing


class AdapixAgent:
    """Workflow-agnostic conversational agent.

    Construct once per (workflow, practice) pair. Reuse across many patients.
    """

    def __init__(
        self,
        workflow: WorkflowConfig,
        practice: PracticeConfig,
        settings: Settings,
    ):
        self.workflow = workflow
        self.practice = practice
        self.settings = settings
        self._client = Anthropic(api_key=settings.anthropic_api_key)

    # ------------------------------------------------------------------
    # Outbound: compose a scheduled cadence message
    # ------------------------------------------------------------------

    def compose_message(
        self,
        *,
        day: int,
        channel: str,
        intent: str,
        patient_context: str,
        conversation_history: list[dict[str, Any]] | None = None,
    ) -> MessagePlan:
        system = self._outbound_system_prompt(day, channel, intent)
        messages: list[dict[str, Any]] = list(conversation_history or [])
        messages.append(
            {
                "role": "user",
                "content": (
                    f"PATIENT CONTEXT\n{patient_context}\n\n"
                    f"Compose the {channel} message for day {day} of this workflow. "
                    f"Intent: {intent}"
                ),
            }
        )

        response = self._client.messages.create(
            model=self.settings.adapix_model,
            max_tokens=1024,
            system=system,
            messages=messages,
        )
        raw = response.content[0].text.strip()
        return self._parse_output(channel, raw)

    # ------------------------------------------------------------------
    # Inbound: respond to a parent's reply
    # ------------------------------------------------------------------

    def respond_to_inbound(
        self,
        inbound_text: str,
        conversation_history: list[dict[str, Any]] | None = None,
        *,
        patient_memory: str = "",
    ) -> MessagePlan:
        """Compose an SMS reply to an inbound message.

        Used by the inbound processor when the message is classified as a normal
        conversational reply (financing questions, scheduling, thanks, general
        questions). Clinical questions, callbacks, declines, and emergencies are
        handled by the inbound processor with templated acknowledgments and do
        NOT pass through this method.

        patient_memory: formatted block of what's been learned about THIS
        contact specifically (patient_memory.format_memory) — separate from
        additional_knowledge, which is about the business, not the customer.
        """
        system = self._reply_system_prompt(patient_memory=patient_memory)
        messages: list[dict[str, Any]] = list(conversation_history or [])
        messages.append({"role": "user", "content": inbound_text})

        response = self._client.messages.create(
            model=self.settings.adapix_model,
            max_tokens=512,
            system=system,
            messages=messages,
        )
        raw = response.content[0].text.strip()
        return MessagePlan(channel="sms", subject=None, body=raw, raw=raw)

    # ------------------------------------------------------------------
    # Prompt construction
    # ------------------------------------------------------------------

    def _sender_identity(self) -> str:
        """Who the first message says it's from. 'Rocco from Rocco's Plumbing'
        when an owner name is set (and the business opted to use it), else just
        'Rocco's Plumbing' — never a dangling 'from' or the word 'there'."""
        owner = (self.practice.doctor_name or "").strip()
        business = (self.practice.name or "").strip() or "us"
        return f"{owner} from {business}" if owner else business

    def _outbound_system_prompt(self, day: int, channel: str, intent: str) -> str:
        voice = self.workflow.voice or {}
        forbidden = voice.get("forbidden_phrases") or []
        escalation_lines = "\n".join(
            f"- If {rule.trigger} -> {rule.action}" for rule in self.workflow.escalation
        ) or "- (no escalation rules configured)"
        return SYSTEM_PROMPT_TEMPLATE.format(
            practice_name=self.practice.name,
            workflow_name=self.workflow.name,
            workflow_objective=self.workflow.objective.strip(),
            sender_identity=self._sender_identity(),
            doctor_name=self.practice.doctor_name,
            office_phone=self.practice.office_phone,
            office_hours=self.practice.office_hours,
            treatment_duration=self.practice.typical_treatment_duration or "varies by case",
            financing_options=self._financing_str(),
            additional_knowledge=self._additional_knowledge_str(),
            warmth=voice.get("warmth", "medium"),
            formality=voice.get("formality", "medium"),
            audience=voice.get("audience", "patient or parent"),
            forbidden_phrases=", ".join(forbidden) or "(none)",
            day=day,
            channel=channel,
            intent=intent,
            escalation_rules=escalation_lines,
        )

    def _reply_system_prompt(self, *, patient_memory: str = "") -> str:
        voice = self.workflow.voice or {}
        forbidden = voice.get("forbidden_phrases") or []
        return REPLY_SYSTEM_TEMPLATE.format(
            practice_name=self.practice.name,
            workflow_name=self.workflow.name,
            workflow_objective=self.workflow.objective.strip(),
            sender_identity=self._sender_identity(),
            doctor_name=self.practice.doctor_name,
            office_phone=self.practice.office_phone,
            office_hours=self.practice.office_hours,
            treatment_duration=self.practice.typical_treatment_duration or "varies by case",
            financing_options=self._financing_str(),
            additional_knowledge=self._additional_knowledge_str(),
            patient_memory=patient_memory,
            warmth=voice.get("warmth", "medium"),
            formality=voice.get("formality", "medium"),
            audience=voice.get("audience", "patient or parent"),
            forbidden_phrases=", ".join(forbidden) or "(none)",
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _financing_str(self) -> str:
        """Real financing terms if the business has actually listed any —
        NEVER a made-up default. financing_options is empty for every
        DB-backed org today (load_practice() never populates it — services
        & pricing flow through additional_knowledge instead), so a "helpful"
        fallback like a fixed string here would have the AI claim every
        single Adapix customer offers financing, whether that's true or
        not. Confirmed: this exact bug caused an unprompted "we offer
        in-house financing" reply to a real customer."""
        if self.practice.financing_options:
            return ", ".join(self.practice.financing_options)
        return (
            "not listed — do NOT tell the customer financing is available "
            "or describe any financing terms; if asked, say you'll check "
            "with the owner and follow up"
        )

    def _additional_knowledge_str(self) -> str:
        additional = self.practice.additional_knowledge or {}
        if not additional:
            return "(none)"
        return "\n".join(f"- {k}: {v}" for k, v in additional.items())

    @staticmethod
    def _parse_output(channel: str, raw: str) -> MessagePlan:
        """Parse channel-specific output (e.g. extract email subject line)."""
        if channel == "email":
            lines = raw.splitlines()
            subject = None
            body_start = 0
            if lines and lines[0].lower().startswith("subject:"):
                subject = lines[0].split(":", 1)[1].strip()
                body_start = 1
                while body_start < len(lines) and not lines[body_start].strip():
                    body_start += 1
            body = "\n".join(lines[body_start:]).strip()
            return MessagePlan(channel="email", subject=subject, body=body, raw=raw)
        return MessagePlan(channel=channel, subject=None, body=raw, raw=raw)
